# Generated by Django 4.1.2 on 2023-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='defineuser',
            name='auth_token',
            field=models.CharField(default='abcdef', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defineuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
